### ISSUE TITLE
Feature request: Show IP in hexadecimal

### ISSUE THREAD

**Issue by ivoruetsche** [dreibh/subnetcalc#10]
Hi

For the [PXE boot process](https://wiki.syslinux.org/wiki/index.php?title=PXELINUX#Configuration), we need the IP address as an uppercase, hexadecimal address

Would be nice, to have this information as well on the output.

gruss ivo

**Comment by dreibh** [comment]
This is quite easy to implement. Check the new branch "dreibh/hex-address" which implements the feature.

**Comment by dreibh** [comment]
Merged into master branch.

**Comment by dreibh** [comment]
Closed.
