### ISSUE TITLE
IPv6 calulation Host Range for /127 and /128 seem wrong

### ISSUE THREAD

**Issue by ohauer** [dreibh/subnetcalc#3]
subnetcalc 2001:db8::1/127
Network       = 2001:db8:: / 127
Netmask       = ffff:ffff:ffff:ffff:ffff:ffff:ffff:fffe
Wildcard Mask = ::1
Hosts Bits    = 1
Max. Hosts    = 1   (2^1 - 1)
Host Range    = { 2001:db8::1 - 2001:db8::1 }
Properties    =   - 2001:db8::1 is a HOST address in 2001:db8::/127

subnetcalc  2001:db8::1/128
Network       = 2001:db8::1 / 128
Netmask       = ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
Wildcard Mask = ::
Hosts Bits    = 0
Max. Hosts    = 0   (2^0 - 1)
Host Range    = { 2001:db8::2 - 2001:db8::1 }
Properties    =   - 2001:db8::1 is a NETWORK address

Seems the host range for the /128 loopback is wrong ( :2 > :1)
Using /128 for loopback and /127 for router <--> router is a valid usage

**Comment by dreibh** [comment]
Fixed in ebb04acc5cb48e9fa89504827b7e139efb5fab59. Thanks for the bug report!
