### ISSUE TITLE
tar.gz files differs on homepage and on GH

### ISSUE THREAD

**Issue by slavkoja** [dreibh/subnetcalc#4]
Downloaded source packages from homepage (subnetcalc-2.4.9.tar.gz) and from github (subnetcalc-subnetcalc-2.4.9.tar.gz) differs in content (and then in size of course), see:
```
-rw-r--r-- 1 user group  69257 Jun  9 07:31 subnetcalc-2.4.9.tar.gz
-rw-r--r-- 1 user group  77616 Jun  9 07:25 subnetcalc-subnetcalc-2.4.9.tar.gz
```
Which one is the right to build it?

And no one has the configure script, as described in INSTALL.

**Comment by dreibh** [comment]
The packages on the homepage (https://www.uni-due.de/~be0001/subnetcalc/) are the original version. They are GnuPG-signed as well, so you check verify them with:
gpg --verify subnetcalc-<VERSION>.tar.xz.asc subnetcalc-<VERSION>.tar.xz
