### ISSUE TITLE
Does subnetcalc support GeoIP 2?

### ISSUE THREAD

**Issue by driesmp** [dreibh/subnetcalc#5]
On FreeBSD, subnetcalc depends on GeoIP which has been marked deprecated. This begs me the question if we can simply change the depend of the port to GeoIP 2?

> Message from GeoIP-1.6.12_3:
> This port is deprecated; you may wish to reconsider installing it:
> Legacy databases no longer available. Switch to GeoIP2 instead.
> It is scheduled to be removed on or after 2019-02-01.

**Comment by dreibh** [comment]
There seems to be no C library "GeoIP2", just libmaxminddb. The latest version of SubNetCalc now builds without GeoIP1 dependency under FreeBSD (port updated: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=239854), i.e. without compiling in the geo-location feature. SubNetCalc still needs to be ported to libmaxminddb to make this feature again available under FreeBSD.

**Comment by driesmp** [comment]
Thanks for pushing an update! I didn't realize geoip2 was not in the tree.

**Comment by driesmp** [comment]
Commited in svn repo. Thanks!
